### ISSUE TITLE
Something is broken if i inject Sentry via IoC container

### ISSUE THREAD

**Issue by Schnoop** [cartalyst/sentry#506]
I would like to inject Sentry in a Command:

```php
<?php namespace MyTest\Commands;

use MyTest\Commands\Command;

use Illuminate\Contracts\Bus\SelfHandling;
use MyTest\User;

class UserSubscribeToNewsletter extends Command implements SelfHandling
{

    /**
     * Id of user to add to newsletter group
     *
     * @var int
     */
    protected $id;

    /**
     * Construct
     *
     * @param int $id
     *
     * @return UserSubscribeToNewsletter
     */
    public function __construct($id)
    {
        $this->id = $id;
    }

    /**
     * Attach user to newsletter group
     *
     * @param Sentry $sentry
     *
     * @return User
     * @throws Exception
     */
    public function handle(Sentry $sentry)
    {
		$user = $sentry->findUserById($this->id);
		
		// User is an instance of \Cartalyst\Sentry\Users\Eloquent\User
		// But i configured "MyTest\User" in the published cartalyst.sentry.php config 
		
		......
    }
}
```

I seems that Sentry is not respecting the published config file when used via Ioc. If i use Sentry via fascade like 

```php
<?php

$user = Sentry::findUserById($id)
```

all is fine.

**Comment by brunogaspar** [comment]
I don't see where you're importing Sentry on your class, only the injection on the constructor.

**Comment by Schnoop** [comment]
Well, that was a copy and paste failure. Sorry for that.

```php
<?php namespace MyTest\Commands;

use MyTest\Commands\Command;

use Cartalyst\Sentry\Sentry;
use Illuminate\Contracts\Bus\SelfHandling;
use MyTest\User;
.....
```

As written in the docs:

> The handle method may also type-hint dependencies, and they will be automatically injected by the IoC container.

**Comment by brunogaspar** [comment]
If the injection is not working, use `app('sentry')` inside your handle method as i don't remember Sentry being prepped to work like this.

**Comment by levacic** [comment]
@brunogaspar FWIW, all that would required injection to work would be to add:

```
$this->app->alias('sentry', 'Cartalyst\Sentry\Sentry');
```

to the end of [SentryServiceProvider::registerSentry()](https://github.com/cartalyst/sentry/blob/2.1/src/Cartalyst/Sentry/SentryServiceProvider.php#L278-L297) - would you accept a PR for this?

@Schnoop If Cartalyst won't do this, I think it would work if you were to do the exact same thing in a provider of your own, like `SentryInjectionServiceProvider`.

But yeah, injecting the instance is much cleaner, rather than doing `app('sentry')->findUserById()`, or `\Sentry::findUserById()`, or at least I find it so at the moment. So it would be great if this was supported out of the box.

**Comment by brunogaspar** [comment]
@levacic Yeap i'm perfectly aware of that, we use them on our other packages. You can send a PR to 2.1 branch if you can :) i'll then merge it to master and the Laravel 5 feature branch.

**Comment by levacic** [comment]
@brunogaspar Here you go: #507 :)

**Comment by brunogaspar** [comment]
Merged, thanks @levacic.
