### ISSUE TITLE
Laravel 4.2, SQLSTATE[42S22]: Column not found

### ISSUE THREAD

**Issue by Lunariel** [cartalyst/sentry#512]
Hello,
When calling $user->hasAccess(...) or any other method using the users_groups table
i got:
```
Illuminate\Database\QueryException thrown with message "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l4_users_groups.sentry_user_id' in 'field list' (SQL: select `l4_users`.*, `l4_users_groups`.`group_id` as `pivot_group_id`, `l4_users_groups`.`sentry_user_id` as `pivot_sentry_user_id` from `l4_users` inner join `l4_users_groups` on `l4_users`.`id` = `l4_users_groups`.`sentry_user_id` where `l4_users_groups`.`group_id` = 20)"
```

The problem come from sentry_user_id can't be found in the table.
The sentry migration use user_id.

I need to change something in the config file for solve that?
Thanks if you can help me.

My sentry version:
```
    "name": "cartalyst/sentry",
     "version": "2.1.x-dev",
     "source": {
         "type": "git",
         "url": "https://github.com/cartalyst/sentry.git",
         "reference": "a93e6b952f1aea024777a65d913168580af6c8e5"
     }
```

ps: sorry for my bad english ^^

**Comment by brunogaspar** [comment]
What steps did you use to install Sentry?

I can't reproduce any issue on my end with Laravel 4.2.17 and Sentry 2.1.x-dev a93e6b9

**Comment by brunogaspar** [comment]
I'll paste the steps i used:

- composer create-project laravel/laravel laravel-4.2 --prefer-dist 4.2
- cd laravel-4.2
- composer require cartalyst/sentry 2.1
- Updated my app/config/database.php file with a database prefix `l4_`
- Ran php artisan migrate --package=cartalyst/sentry
- Created a dummy user on my `l4_users` table
- On my `app/routes.php` file i used the following to test
```
$user = Sentry::findUserById(1);

Sentry::login($user);

var_dump($user->hasAccess('foo'));

var_dump(Sentry::hasAccess('admin'));
```
It's showing false two times as expected since the user doesn't have any permissions or any groups attached.
- Changed the dependency on my composer.json to `2.1.*@dev` then ran composer update and i've hit the routes again, still working.
- Ran the snippet above again, same results.

--

Either you messed up somewhere, or you're missing a step.

**Comment by Lunariel** [comment]
Thanks for your answers,
I have updated from laravel 4.1 and sentry 2.x (i don't remember the exact version)

I'll try, to install a clean version.
I can't use my computer for a week, i say you if it work when i'm back.

**Comment by brunogaspar** [comment]
Ok, let me know if you still have that issue.

**Comment by Lunariel** [comment]
Thanks for your help, with a new install it work perfectly.
Maybe i got a problem on update.
