### ISSUE TITLE
Package Update User is not supported/ not working

### ISSUE THREAD

**Issue by seiccn** [cartalyst/sentry#515]
Please check http://stackoverflow.com/questions/28847090/laravel-sentry-update-the-user It seems that your package has an error there.
It says that user->save is an undefined method. The problem is that it cannot find the user by ID and is instead returning all the users.

I had programmed everything with your package but will have to switch to the standard Auth.

**Comment by brunogaspar** [comment]
Feel free to submit a PR with a fix.

**Comment by seiccn** [comment]
I do not have a fix for it. That's why I was asking. You are basically
blowing up my masters thesis, I was really hoping to get some help with it.

Can you help me? I do not understand the inside of your code.

**Comment by brunogaspar** [comment]
@seiccn my suggestion is for you to debug your code first, maybe do `dd($user);` and see what it returns and start from there.

You can look [here](https://github.com/cartalyst/sentry/blob/2.1/src/Cartalyst/Sentry/Users/Eloquent/Provider.php#L71-L80) too since you say that the problem is probably there.

Sorry if i can't be of better assistance, but i don't have time to setup an environment with Sentry at the moment to try to replicate your issue, sorry.
