### ISSUE TITLE
Support for secure cookies

### ISSUE THREAD

**Issue by LucanFahr** [cartalyst/sentry#516]
I am using Sentry 2 with Laravel 4.2, running a website over HTTPS. The cookies transmitted by Sentry do not allow for the secure attribute to be set, which creates a potential security vulnerability.

I dug into the sources and found that Cartalyst\Sentry\Cookies\IlluminateCookie (and possibly others, I did not check) has no way to set the secure parameter to true in the make( ) and forever( ) calls.

I was hoping this could be implemented based on a configuration setting (not all environments will require secure to be true). I will fix the IlluminateCookie myself and make a commit shortly.

**Comment by levacic** [comment]
It's actually not hard to extend Sentry's `IlluminateCookie`, inject a new boolean argument `$secure` through the constructor, and create your own service provider to override `sentry.cookie` with your own code (just copy `SentryServiceProvider::registerCookie()` and instantiate your own cookie, passing secure, for example, from `$app['config']['session.secure']` - since it seems natural that if you have configured your session cookies to be secure, you'd want the "remember me" cookies secure as well).

The, in your custom `IlluminateCookie` class, override the `put()` and `forever()` methods to pass `$this->secure` to calls to `$this->jar->make()` and `$this->jar->forever()`, respectively.

Of course, it would be awesome to have this in the Sentry core, and I'd consider this a bugfix rather than a feature (since insecure cookies are certainly a bug), but since Sentry development is currently on hold, I just wanted to give some input on how to accomplish this on your own.

Cheers!

**Comment by brunogaspar** [comment]
Just change this setting on your Laravel application.

**Comment by LucanFahr** [comment]
In the session config? Will Sentry use that?
