### ISSUE TITLE
'foo.bar'->hasPermission('foo.*') should return false

### ISSUE THREAD

**Issue by aleemb** [cartalyst/sentry#541]
If a user has the permission 'foo.bar' then a check against `hasPermission('foo.*')` should return `false` IMO since the latter implies that the user has access to everything under `foo` which isn't the case. I suspect this is a bug since a user with `'foo.bar'` should not have access to all resources under `'foo'` and especially not `'foo.*'`.

The implementation references #123 but that was more about giving user access to `foo.*` and checking if `'foo.*'->hasPermission('foo.bar')` should return true, which Sentry already does.

**Comment by brunogaspar** [comment]
We're open to PR's.

**Comment by aleemb** [comment]
I'd be happy to send in a PR if you can acknowledge this is a bug and re-open it.

**Comment by aleemb** [comment]
@brunogaspar FWIW, I had sent a PR against #131 which was also related to wildcards. Not sure if you closed this accidentally but would be good to get some clarity so I can go ahead and fix this up.

**Comment by brunogaspar** [comment]
Sorry if it's not the reply you were expecting, but we're not maintaining Sentry at this point, however we're open to PR's which fixes bugs.

The reason for this is that we'll be open sourcing Sentinel tomorrow. 

But anyway, since you've submitted the PR to introduce wildcard permission support, if you see this is a bug you can try to patch it, for sure, and submit a PR with tests.
